const albumList = [
  {
    album_id: 1,
    album_comments: 0,
    album_date_created: "11/26/2008 01:44:45 AM",
    album_date_released: "1/05/2009",
    album_engineer: "",
    album_favorites: 4,
    album_handle: "AWOL_-_A_Way_Of_Life",
    album_image_file: "https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg",
    album_images: "[{'image_id': '1955', 'image_file': 'https://freemusicarchive.org/file/images/artists/AWOL_-_2009113014453413.jpg', 'image_title': 'artists Image', 'image_caption': 'azillion records', 'image_copyright': None, 'image_source': None}]",
    album_information: "<p></p>",
    album_listens: 6073,
    album_producer: "",
    album_title: "AWOL - A Way Of Life",
    album_tracks: 7,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/",
    artist_name: "AWOL",
    artist_url: "http://freemusicarchive.org/music/AWOL/",
    tags: []
  },
  {
    album_id: 100,
    album_comments: 0,
    album_date_created: "11/26/2008 01:55:44 AM",
    album_date_released: "1/09/2009",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "On_Opaque_Things",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Bird_Names_-_On_Opaque_Things_-_20100201151648616.jpg",
    album_images: "[{'image_id': '4403', 'image_file': 'https://freemusicarchive.org/file/images/artists/Chandeliers_-_2009113014608987.png', 'image_title': 'artists Image', 'image_caption': None, 'image_copyright': None, 'image_source': None}, {'image_id': '4328', 'image_file': 'https://freemusicarchive.org/file/images/artists/Chandeliers_-_2009113014607953.jpg', 'image_title': 'artists Image', 'image_caption': None, 'image_copyright': None, 'image_source': None}]",
    album_information: "",
    album_listens: 5613,
    album_producer: "",
    album_title: "On Opaque Things",
    album_tracks: 4,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/Bird_Names/On_Opaque_Things/",
    artist_name: "Bird Names",
    artist_url: "http://freemusicarchive.org/music/Bird_Names/",
    tags: []
  },
  {
    album_id: 1000,
    album_comments: 0,
    album_date_created: "12/04/2008 09:28:49 AM",
    album_date_released: "10/26/2008",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "DMBQ_Live_at_2008_Record_Fair_on_WFMU_Record_Fairs_Show_on_10262008",
    album_image_file: "https://freemusicarchive.org/file/images/albums/DMBQ_-_DMBQ_Live_at_2008_Record_Fair_on_WFMU_Record_Fairs_Show_on_10262008_-_2009113012327417.jpg",
    album_images: "[{'image_id': '31997', 'image_file': 'https://freemusicarchive.org/file/images/artists/Marzipan_Marzipan_-_20151120162333592.jpg', 'image_title': 'Artist Image: Marzipan Marzipan', 'image_caption': 'Marzipan Marzipan', 'image_copyright': None, 'image_source': None}]",
    album_information: "<p>http://blog.wfmu.org/freeform/2008/10/what-were-we-th.html</p><p><br /></p>",
    album_listens: 1092,
    album_producer: "",
    album_title: "DMBQ Live at 2008 Record Fair on WFMU Record Fair's Show on 10/26/2008",
    album_tracks: 4,
    album_type: "Live Performance",
    album_url: "http://freemusicarchive.org/music/DMBQ/DMBQ_Live_at_2008_Record_Fair_on_WFMU_Record_Fairs_Show_on_10262008/",
    artist_name: "DMBQ",
    artist_url: "http://freemusicarchive.org/music/DMBQ/",
    tags: []
  },
  {
    album_id: 10000,
    album_comments: 0,
    album_date_created: "9/05/2011 04:42:57 PM",
    album_date_released: "",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "Live_at_CKUT_on_Montreal_Sessions_1434",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Sundrips_-_Live_at_CKUT_on_Montreal_Sessions_-_20110905175626878.jpg",
    album_images: "[{'image_id': '12266', 'image_file': 'https://freemusicarchive.org/file/images/artists/Jack_Hertz_PHOBoS_Blue_Hell_-_20110121140650772.jpg', 'image_title': 'Artist Image: Jack Hertz, PHOBoS, Blue Hell', 'image_caption': \"Jack Hertz, PHOBoS, Blue Hell - 'Gritty Transmutation (Dedicated to Peter 'Sleazy' Christopherson)'\", 'image_copyright': 'Jack Hertz, PHOBoS, Blue Hell', 'image_source': 'http://surrism.phonoethics.com/surrism-phonoethics_jack_hertz_phobos_blue_hell_-_gritty_transmutatio'}]",
    album_information: "<p>Live Set on the Montreal Session February 22 curtated by Frank \"<a href=\"http://hobocult.blogspot.com/\">Hobo Cubes</a>\" Ouellette</p>",
    album_listens: 1001,
    album_producer: "",
    album_title: "Live at CKUT on Montreal Sessions",
    album_tracks: 1,
    album_type: "Radio Program",
    album_url: "http://freemusicarchive.org/music/Sundrips/Live_at_CKUT_on_Montreal_Sessions_1434/",
    artist_name: "Sundrips",
    artist_url: "http://freemusicarchive.org/music/Sundrips/",
    tags: []
  },
  {
    album_id: 10001,
    album_comments: 0,
    album_date_created: "9/06/2011 12:02:58 AM",
    album_date_released: "1/01/2006",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "Grounds_Dream_Cosmic_Love",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Uton_-_Grounds_Dream_Cosmic_Love_-_2011090602130635.jpg",
    album_images: "[{'image_id': '24091', 'image_file': 'https://freemusicarchive.org/file/images/artists/Nick_Rivera_-_2013062853731724.jpg', 'image_title': 'Artist Image: Nick Rivera', 'image_caption': None, 'image_copyright': None, 'image_source': None}]",
    album_information: "<p>Recorded in Linnavuori, Finland, 2005 (with cassette four-track recorder). Originally released on CDR by Students Of Decay, 2006.</p>",
    album_listens: 504,
    album_producer: "",
    album_title: "Ground's Dream Cosmic Love",
    album_tracks: 1,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/Uton/Grounds_Dream_Cosmic_Love/",
    artist_name: "Uton",
    artist_url: "http://freemusicarchive.org/music/Uton/",
    tags: []
  },
  {
    album_id: 10002,
    album_comments: 0,
    album_date_created: "9/06/2011 12:53:01 AM",
    album_date_released: "",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "Trust_Now",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Prince_Rama_-_Trust_Now_-_20110908154312339.jpg",
    album_images: "[{'image_id': '12270', 'image_file': 'https://freemusicarchive.org/file/images/artists/Carlos_Ramirez_-_20110122111456036.jpg', 'image_title': 'Artist Image: Carlos Ramirez', 'image_caption': 'Carlos Ramirez', 'image_copyright': 'Carlos Ramirez', 'image_source': 'http://www.facebook.com/profile.php?id=1648564857&amp;sk=info'}]",
    album_information: "",
    album_listens: 2145,
    album_producer: "",
    album_title: "Trust Now",
    album_tracks: 1,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/Prince_Rama_of_Ayodhya/Trust_Now/",
    artist_name: "Prince Rama",
    artist_url: "http://freemusicarchive.org/music/Prince_Rama_of_Ayodhya/",
    tags: []
  },
  {
    album_id: 10003,
    album_comments: 0,
    album_date_created: "9/06/2011 05:46:22 AM",
    album_date_released: "9/06/2011",
    album_engineer: "",
    album_favorites: 1,
    album_handle: "Or_Up_We_Fall",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Fanas_-_Or_Up_We_Fall_-_2011090664703097.jpg",
    album_images: "[{'image_id': '12274', 'image_file': 'https://freemusicarchive.org/file/images/artists/Evening_Fires_-_20110122121025490.jpg', 'image_title': 'artists Image', 'image_caption': None, 'image_copyright': None, 'image_source': None}]",
    album_information: "<p><span style=\"color:#222222;font-family:arial, sans-serif;font-size:13px;\">Fanas’ new album “Or up we fall” represents an update to his characteristic sound, his solid base built on funk and classic hip-hop doubtlessly aligning now with the gallery of new generation producers, presided by the unchallenged leader Flying Lotus. You can feel the L.A. atmosphere, straight from the speakers of the Low-End Theory club, post-funk &amp; post-hip-hop animated the whole album, the laid-back samples reaching the erotic g-funk a la Dam Funk &amp; Chromeo zone and the pigmented ambient of the Samiyam and Teebs grooves. Practically, it is one of the most easy-listening productions of the recent underground, the experimental icing leaving the accessibility of the melodies and their club appeal unchanged. </span></p>",
    album_listens: 24745,
    album_producer: "",
    album_title: "Or Up We Fall [LCL08]",
    album_tracks: 21,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/Fanas/Or_Up_We_Fall/",
    artist_name: "Fanas",
    artist_url: "http://freemusicarchive.org/music/Fanas/",
    tags: []
  },
  {
    album_id: 10007,
    album_comments: 0,
    album_date_created: "9/06/2011 07:57:31 PM",
    album_date_released: "10/05/2010",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "none_given_1989",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Chantale_Laplante_and_Martine_Crispo_-_Live_at_CKUT_on_Montreal_Sessions_-_20110906202602575.jpg",
    album_images: "[{'image_id': '15707', 'user_id': None, 'artist_id': None, 'album_id': '10007', 'curator_id': None, 'image_file': 'https://freemusicarchive.org/file/images/albums/Chantale_Laplante_and_Martine_Crispo_-_Live_at_CKUT_on_Montreal_Sessions_-_20110906202602575.jpg', 'image_title': 'Album Image: Live at CKUT on Montreal Sessions', 'image_caption': None, 'image_copyright': None, 'image_source': None, 'image_order': '0'}]",
    album_information: "<p>Live improvisation between two pioneers on the montreal sound art scene, Martine Crispo and Chantale Laplane during the October 2010 Montreal Sessions renamed Esclandres Montrealaises hosted and produced by Chantale LAplante</p>",
    album_listens: 480,
    album_producer: "",
    album_title: "Live at CKUT on Montreal Sessions",
    album_tracks: 1,
    album_type: "Radio Program",
    album_url: "http://freemusicarchive.org/music/Chantale_Laplante_and_Martine_Crispo/none_given_1989/",
    artist_name: "Chantale Laplante and Martine Crispo",
    artist_url: "http://freemusicarchive.org/music/Chantale_Laplante_and_Martine_Crispo/",
    tags: []
  },
  {
    album_id: 10008,
    album_comments: 0,
    album_date_created: "9/06/2011 10:18:42 PM",
    album_date_released: "9/07/2011",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "chamber_music",
    album_image_file: "https://freemusicarchive.org/file/images/albums/barriere_garca_gris_-_chamber_music_-_2011090775833838.jpg",
    album_images: "[{'image_id': '15708', 'user_id': None, 'artist_id': None, 'album_id': '10008', 'curator_id': None, 'image_file': 'https://freemusicarchive.org/file/images/albums/barriere_garca_gris_-_chamber_music_-_2011090775833838.jpg', 'image_title': 'Album Image: chamber music', 'image_caption': None, 'image_copyright': None, 'image_source': None, 'image_order': '0'}]",
    album_information: "<p>bowed metal. electric hum. squeals and squelches. fractured  percussions. is it live? is it electro? low rumbles and fluttering  squeaks. droning tones while construction labors away underneath it all.  wheels and gears. pulsing menace threatens to break free. voices in the  dark. clicks and pops. insects learning. atmospheric radio signals,  clouds roll in. ambiguity.</p>\n<p>lali barriere, miguel garcía and tomas gris documented this  improvised electro-acoustic session in february of 2011. objects were  miked, amplified, not miked, not amplified, etc. electronics were used.  17.54 minutes.</p>\n<p>music by<br /> lali barriere – objects, miguel a. garcía – electronics, tomas gris – objects</p>\n<p>recorded live in arphouse, madrid, 11-2-11. edited by miguel a.  garcía. mastered by ferran fages &amp; tzesne. drawing by raúl domínguez</p>",
    album_listens: 356,
    album_producer: "",
    album_title: "chamber music",
    album_tracks: 1,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/barriere_garca_gris/chamber_music/",
    artist_name: "barriere, garcía, gris",
    artist_url: "http://freemusicarchive.org/music/barriere_garca_gris/",
    tags: []
  },
  {
    album_id: 10009,
    album_comments: 0,
    album_date_created: "9/07/2011 08:45:11 AM",
    album_date_released: "",
    album_engineer: "",
    album_favorites: 0,
    album_handle: "My_Song",
    album_image_file: "https://freemusicarchive.org/file/images/albums/Audio_K_-_My_Song_-_2011090790427335.JPG",
    album_images: "[{'image_id': '15712', 'user_id': None, 'artist_id': None, 'album_id': '10009', 'curator_id': None, 'image_file': 'https://freemusicarchive.org/file/images/albums/Audio_K_-_My_Song_-_2011090790427335.JPG', 'image_title': 'albums Image', 'image_caption': None, 'image_copyright': None, 'image_source': None, 'image_order': '0'}]",
    album_information: "",
    album_listens: 9705,
    album_producer: "",
    album_title: "My Song",
    album_tracks: 4,
    album_type: "Album",
    album_url: "http://freemusicarchive.org/music/Audio_K/My_Song/",
    artist_name: "Audio K",
    artist_url: "http://freemusicarchive.org/music/Audio_K/",
    tags: []
  }
]

module.exports = {albumList};


