const trackList = [
    {
      "track_id": 2,
      "album_id": 1,
      "album_title": "AWOL - A Way Of Life",
      "album_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/",
      "artist_id": 1,
      "artist_name": "AWOL",
      "artist_url": "http://freemusicarchive.org/music/AWOL/",
      "artist_website": "http://www.AzillionRecords.blogspot.com",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-sa.png",
      "license_parent_id": 5,
      "license_title": "Attribution-NonCommercial-ShareAlike 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:48:12 AM",
      "track_date_recorded": "11/26/2008",
      "track_disc_number": 1,
      "track_duration": "2:48",
      "track_explicit": "Radio-Unsafe",
      "track_explicit_notes": "",
      "track_favorites": 2,
      "track_file": "music/WFMU/AWOL/AWOL_-_A_Way_Of_Life/AWOL_-_03_-_Food.mp3",
      "track_genres": "[{'genre_id': '21', 'genre_title': 'Hip-Hop', 'genre_url': 'http://freemusicarchive.org/genre/Hip-Hop/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 4656,
      "track_language_code": "en",
      "track_listens": 1293,
      "track_lyricist": "",
      "track_number": 3,
      "track_publisher": "",
      "track_title": "Food",
      "track_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/Food"
    },
    {
      "track_id": 3,
      "album_id": 1,
      "album_title": "AWOL - A Way Of Life",
      "album_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/",
      "artist_id": 1,
      "artist_name": "AWOL",
      "artist_url": "http://freemusicarchive.org/music/AWOL/",
      "artist_website": "http://www.AzillionRecords.blogspot.com",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-sa.png",
      "license_parent_id": 5,
      "license_title": "Attribution-NonCommercial-ShareAlike 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:48:14 AM",
      "track_date_recorded": "11/26/2008",
      "track_disc_number": 1,
      "track_duration": "3:57",
      "track_explicit": "Radio-Unsafe",
      "track_explicit_notes": "",
      "track_favorites": 1,
      "track_file": "music/WFMU/AWOL/AWOL_-_A_Way_Of_Life/AWOL_-_04_-_Electric_Ave.mp3",
      "track_genres": "[{'genre_id': '21', 'genre_title': 'Hip-Hop', 'genre_url': 'http://freemusicarchive.org/genre/Hip-Hop/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 1470,
      "track_language_code": "en",
      "track_listens": 514,
      "track_lyricist": "",
      "track_number": 4,
      "track_publisher": "",
      "track_title": "Electric Ave",
      "track_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/Electric_Ave"
    },
    {
      "track_id": 5,
      "album_id": 1,
      "album_title": "AWOL - A Way Of Life",
      "album_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/",
      "artist_id": 1,
      "artist_name": "AWOL",
      "artist_url": "http://freemusicarchive.org/music/AWOL/",
      "artist_website": "http://www.AzillionRecords.blogspot.com",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-sa.png",
      "license_parent_id": 5,
      "license_title": "Attribution-NonCommercial-ShareAlike 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:48:20 AM",
      "track_date_recorded": "11/26/2008",
      "track_disc_number": 1,
      "track_duration": "3:26",
      "track_explicit": "Radio-Unsafe",
      "track_explicit_notes": "",
      "track_favorites": 6,
      "track_file": "music/WFMU/AWOL/AWOL_-_A_Way_Of_Life/AWOL_-_06_-_This_World.mp3",
      "track_genres": "[{'genre_id': '21', 'genre_title': 'Hip-Hop', 'genre_url': 'http://freemusicarchive.org/genre/Hip-Hop/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 1933,
      "track_language_code": "en",
      "track_listens": 1151,
      "track_lyricist": "",
      "track_number": 6,
      "track_publisher": "",
      "track_title": "This World",
      "track_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/This_World"
    },
    {
      "track_id": 10,
      "album_id": 6,
      "album_title": "Constant Hitmaker",
      "album_url": "http://freemusicarchive.org/music/Kurt_Vile/Constant_Hitmaker/",
      "artist_id": 6,
      "artist_name": "Kurt Vile",
      "artist_url": "http://freemusicarchive.org/music/Kurt_Vile/",
      "artist_website": "http://kurtvile.com",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 192000,
      "track_comments": 0,
      "track_composer": "Kurt Vile",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/25/2008 05:49:06 PM",
      "track_date_recorded": "11/26/2008",
      "track_disc_number": 1,
      "track_duration": "2:41",
      "track_explicit": "Radio-Safe",
      "track_explicit_notes": "",
      "track_favorites": 178,
      "track_file": "music/WFMU/Kurt_Vile/Constant_Hitmaker/Kurt_Vile_-_01_-_Freeway.mp3",
      "track_genres": "[{'genre_id': '10', 'genre_title': 'Pop', 'genre_url': 'http://freemusicarchive.org/genre/Pop/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Kurt_Vile_-_Constant_Hitmaker_-_2009113012923399.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 54881,
      "track_language_code": "en",
      "track_listens": 50135,
      "track_lyricist": "",
      "track_number": 1,
      "track_publisher": "",
      "track_title": "Freeway",
      "track_url": "http://freemusicarchive.org/music/Kurt_Vile/Constant_Hitmaker/Freeway"
    },
    {
      "track_id": 20,
      "album_id": 4,
      "album_title": "Niris",
      "album_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/",
      "artist_id": 4,
      "artist_name": "Nicky Cook",
      "artist_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/",
      "artist_website": "",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:48:56 AM",
      "track_date_recorded": "1/01/2008",
      "track_disc_number": 1,
      "track_duration": "5:11",
      "track_explicit": "",
      "track_explicit_notes": "",
      "track_favorites": 0,
      "track_file": "music/WFMU/Nicky_Cook__Chris_Andrews/Niris/Nicky_Cook__Chris_Andrews_-_03_-_Spiritual_Level.mp3",
      "track_genres": "[{'genre_id': '76', 'genre_title': 'Experimental Pop', 'genre_url': 'http://freemusicarchive.org/genre/Experimental_Pop/'}, {'genre_id': '103', 'genre_title': 'Singer-Songwriter', 'genre_url': 'http://freemusicarchive.org/genre/Singer-Songwriter/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Chris_and_Nicky_Andrews_-_Niris_-_2009113012134556.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 978,
      "track_language_code": "en",
      "track_listens": 361,
      "track_lyricist": "",
      "track_number": 3,
      "track_publisher": "",
      "track_title": "Spiritual Level",
      "track_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/Spiritual_Level"
    },
    {
      "track_id": 26,
      "album_id": 4,
      "album_title": "Niris",
      "album_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/",
      "artist_id": 4,
      "artist_name": "Nicky Cook",
      "artist_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/",
      "artist_website": "",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:49:05 AM",
      "track_date_recorded": "1/01/2008",
      "track_disc_number": 1,
      "track_duration": "3:01",
      "track_explicit": "",
      "track_explicit_notes": "",
      "track_favorites": 0,
      "track_file": "music/WFMU/Nicky_Cook__Chris_Andrews/Niris/Nicky_Cook__Chris_Andrews_-_04_-_Where_is_your_Love.mp3",
      "track_genres": "[{'genre_id': '76', 'genre_title': 'Experimental Pop', 'genre_url': 'http://freemusicarchive.org/genre/Experimental_Pop/'}, {'genre_id': '103', 'genre_title': 'Singer-Songwriter', 'genre_url': 'http://freemusicarchive.org/genre/Singer-Songwriter/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Chris_and_Nicky_Andrews_-_Niris_-_2009113012134556.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 1060,
      "track_language_code": "en",
      "track_listens": 193,
      "track_lyricist": "",
      "track_number": 4,
      "track_publisher": "",
      "track_title": "Where is your Love?",
      "track_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/Where_is_your_Love"
    },
    {
      "track_id": 30,
      "album_id": 4,
      "album_title": "Niris",
      "album_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/",
      "artist_id": 4,
      "artist_name": "Nicky Cook",
      "artist_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/",
      "artist_website": "",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:49:11 AM",
      "track_date_recorded": "1/01/2008",
      "track_disc_number": 1,
      "track_duration": "2:54",
      "track_explicit": "",
      "track_explicit_notes": "",
      "track_favorites": 0,
      "track_file": "music/WFMU/Nicky_Cook__Chris_Andrews/Niris/Nicky_Cook__Chris_Andrews_-_05_-_Too_Happy.mp3",
      "track_genres": "[{'genre_id': '76', 'genre_title': 'Experimental Pop', 'genre_url': 'http://freemusicarchive.org/genre/Experimental_Pop/'}, {'genre_id': '103', 'genre_title': 'Singer-Songwriter', 'genre_url': 'http://freemusicarchive.org/genre/Singer-Songwriter/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Chris_and_Nicky_Andrews_-_Niris_-_2009113012134556.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 718,
      "track_language_code": "en",
      "track_listens": 612,
      "track_lyricist": "",
      "track_number": 5,
      "track_publisher": "",
      "track_title": "Too Happy",
      "track_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/Too_Happy"
    },
    {
      "track_id": 46,
      "album_id": 4,
      "album_title": "Niris",
      "album_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/",
      "artist_id": 4,
      "artist_name": "Nicky Cook",
      "artist_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/",
      "artist_website": "",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:49:53 AM",
      "track_date_recorded": "1/01/2008",
      "track_disc_number": 1,
      "track_duration": "1:44",
      "track_explicit": "",
      "track_explicit_notes": "",
      "track_favorites": 0,
      "track_file": "music/WFMU/Nicky_Cook__Chris_Andrews/Niris/Nicky_Cook__Chris_Andrews_-_08_-_Yosemite.mp3",
      "track_genres": "[{'genre_id': '76', 'genre_title': 'Experimental Pop', 'genre_url': 'http://freemusicarchive.org/genre/Experimental_Pop/'}, {'genre_id': '103', 'genre_title': 'Singer-Songwriter', 'genre_url': 'http://freemusicarchive.org/genre/Singer-Songwriter/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Chris_and_Nicky_Andrews_-_Niris_-_2009113012134556.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 252,
      "track_language_code": "en",
      "track_listens": 171,
      "track_lyricist": "",
      "track_number": 8,
      "track_publisher": "",
      "track_title": "Yosemite",
      "track_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/Yosemite"
    },
    {
      "track_id": 48,
      "album_id": 4,
      "album_title": "Niris",
      "album_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/",
      "artist_id": 4,
      "artist_name": "Nicky Cook",
      "artist_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/",
      "artist_website": "",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-nd.png",
      "license_parent_id": "",
      "license_title": "Attribution-NonCommercial-NoDerivatives (aka Music Sharing) 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-nd/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:49:56 AM",
      "track_date_recorded": "1/01/2008",
      "track_disc_number": 1,
      "track_duration": "3:25",
      "track_explicit": "",
      "track_explicit_notes": "",
      "track_favorites": 0,
      "track_file": "music/WFMU/Nicky_Cook__Chris_Andrews/Niris/Nicky_Cook__Chris_Andrews_-_09_-_Light_of_Light.mp3",
      "track_genres": "[{'genre_id': '76', 'genre_title': 'Experimental Pop', 'genre_url': 'http://freemusicarchive.org/genre/Experimental_Pop/'}, {'genre_id': '103', 'genre_title': 'Singer-Songwriter', 'genre_url': 'http://freemusicarchive.org/genre/Singer-Songwriter/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/Chris_and_Nicky_Andrews_-_Niris_-_2009113012134556.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 247,
      "track_language_code": "en",
      "track_listens": 173,
      "track_lyricist": "",
      "track_number": 9,
      "track_publisher": "",
      "track_title": "Light of Light",
      "track_url": "http://freemusicarchive.org/music/Chris_and_Nicky_Andrews/Niris/Light_of_Light"
    },
    {
      "track_id": 134,
      "album_id": 1,
      "album_title": "AWOL - A Way Of Life",
      "album_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/",
      "artist_id": 1,
      "artist_name": "AWOL",
      "artist_url": "http://freemusicarchive.org/music/AWOL/",
      "artist_website": "http://www.AzillionRecords.blogspot.com",
      "license_image_file": "http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png",
      "license_image_file_large": "http://fma-files.s3.amazonaws.com/resources/img/licenses/by-nc-sa.png",
      "license_parent_id": 5,
      "license_title": "Attribution-NonCommercial-ShareAlike 3.0 International",
      "license_url": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
      "tags": [],
      "track_bit_rate": 256000,
      "track_comments": 0,
      "track_composer": "",
      "track_copyright_c": "",
      "track_copyright_p": "",
      "track_date_created": "11/26/2008 01:43:19 AM",
      "track_date_recorded": "11/26/2008",
      "track_disc_number": 1,
      "track_duration": "3:27",
      "track_explicit": "Radio-Unsafe",
      "track_explicit_notes": "",
      "track_favorites": 3,
      "track_file": "music/WFMU/AWOL/AWOL_-_A_Way_Of_Life/AWOL_-_05_-_Street_Music.mp3",
      "track_genres": "[{'genre_id': '21', 'genre_title': 'Hip-Hop', 'genre_url': 'http://freemusicarchive.org/genre/Hip-Hop/'}]",
      "track_image_file": "https://freemusicarchive.org/file/images/albums/AWOL_-_AWOL_-_A_Way_Of_Life_-_2009113011911435.jpg",
      "track_information": "",
      "track_instrumental": 0,
      "track_interest": 1126,
      "track_language_code": "en",
      "track_listens": 943,
      "track_lyricist": "",
      "track_number": 5,
      "track_publisher": "",
      "track_title": "Street Music",
      "track_url": "http://freemusicarchive.org/music/AWOL/AWOL_-_A_Way_Of_Life/Street_Music"
    }
  ]

module.exports = {trackList};
